export const elements = [
    {
        "name": 'hidrogenio',
        'atomicNumber':'1'
    },
    "he "= "He",
    "li "= "Li",
    "be "= "Be",
    "b "=  "B",
    "c "=  "C",
    "n "=  "N",
    "o "=  "O",
    "f "=  "F",
    "ne "= "Ne",
    "na "= 'Na',
    "mg "= 'Mg',
    "al "= 'Al',
    "si "= 'Si',
    "p "=  'P',
    "s "=  'S',
    "cl "= 'Cl',
    "ar "= 'Ar',
    "k "=  'K',
    "ca "= 'Ca',
    "sc "= 'Sc',
    "ti "= 'Ti',
    "v "=  'V',
    "cr "= 'Cr',
    "mn "= 'Mn',
    "fe "= 'Fe',
    "co "= 'Co',
    "ni "= 'Ni',
    "cu "= 'Cu',
    "zn "= 'Zn',
    "ga "= 'Ga',
    "ge "= 'Ge',
    "as "= 'As',
    "se "= 'Se',
    "br "= 'Br',
    "xr "= 'Xr'
]